### ISSUE TITLE
add blurb about getting test trb on mumbai/goerli

### ISSUE THREAD

**Issue by oraclown** [tellor-io/TellorDocs#109]
so the telliot docs can point to it, rather than changing in multiple places

**Comment by oraclown** [comment]
[related](https://github.com/tellor-io/telliot-feeds/pull/556#pullrequestreview-1242332576)

**Comment by cryptobanjo** [comment]
Added blurb to our Tellor docs (thx spuddy for the copy):  Can be linked to at this url which we can continue to update with more networks without changing the link: [How to get Testnet TRB](https://docs.tellor.io/tellor/the-basics/readme#need-testnet-tokens-trb)
